### ISSUE TITLE
Client: Checkout Page UI

### ISSUE THREAD

**Issue by jake-magri** [parsamh8/Volt-Underground#11]
Checkout page allows users to remove an event, add an event, and asks for payment and email with a purchase button.
When the purchase button is clicked with valid form data, the event will be saved to the user's purchase history in the DB by making a request to the server.

**Comment by parsamh8** [comment]
Let call the page ticketLink if we all agree. Seems like easy to follow for mapping.

**Comment by parsamh8** [comment]
This page direct from **"session page"** &&  also direct from buy ticket button in **"feature component"** on main page.

Content include: 
 - Method of payments: 'Paypal', 'Master', 'Visa' || similiar methods || credit information placeholders. (research needed)
 - posterUrl placeholder.
 - Add ticket option
 - Green bandage appear at footer of the page content with TOTAL PRICE amount (bold) and _state change_ if _add ticket_ clicked to appear **new price** for more than one ticket > 1.

**Comment by jake-magri** [comment]
Everything looks great! We have a couple of milestones to hit before closing this one out:

- [x] Add payment information input form that syncs with Checkout Button. Payment information is validated but not sent to the db at the moment. (https://github.com/users/parsamh8/projects/3/views/2?pane=issue&itemId=90266319)
- [x] Checkout Button sends purchases to server and updates user document with a property called purchase history. The property contains a set of Events that the new Event purchases are appended to.(https://github.com/parsamh8/Volt-Underground/issues/30) This data will be shown in the client user profile.
